### ISSUE TITLE
use timestamps, not time since

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/microkit#23]
I recently read some Prometheus docs. We might do something wrong when emitting the endpoint durations. We emit them as duration. The Prometheus docs recommend emitting timestamps. What do you think @JosephSalisbury 

See
- https://github.com/giantswarm/microkit/blob/dfe4216baddfe4dffce4b0713ab3af56a8f9f769/server/server.go#L220
- https://prometheus.io/docs/practices/instrumentation/#timestamps-not-time-since

**Comment by JosephSalisbury** [comment]
I think there's a small nuance here.

The documentation refers to measuring the time _since_ something took place, and then recommends exporting the unix timestamp - this makes sense.

In our case of endpoint durations, this is the amount of time the endpoint took to complete. I would say exporting the duration makes sense. We can't use `time() - my_timestamp_metric` to calculate how long it took an endpoint to complete - this would be the time since the endpoint completed.

**Comment by xh3b4sd** [comment]
Totally makes sense. Vacation brain wasn't certain.
